spring:

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:15432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  flyway:
    out-of-order: true

server:
  port: 8089

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG