api-version: v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # for docker db
#    username: demouser
#    password: demopassword
#    url: jdbc:postgresql://localhost:15432/postgres
    # for local db
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    open-in-view: true # TODO: change to false later
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        order_by.default_null_ordering: last
  flyway:
    validate-on-migrate: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: idkspbcorp@gmail.com
    password: idkspbcorp777
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
            scope: 'email,profile,openid'

  # For Handling NoHandlerFoundException
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

#logging:
#  level:
#    org:
#      apache:
#        tomcat: INFO
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: DEBUG

jwt:
  token:
    secret: jwtdevblog
    expired: 60 # minute

app:
  google:
    redirect:
      url: http://localhost:8080/v1/users/%s/articles
mail:
  name: IDK
  email: idkspbcorp.com
  url: http://localhost:8080/v1/users/[[userId]]/verify?code=[[code]]
  subject: Подтверждение регистрации
  content: >-
    Приветствуем, [[name]]!<br>
    Для подтверждения электронной почты и завершения процесса регистрации,
    пожалуйста, пройдите по ссылке:<br>
    <h3><a href="[[URL]]" target="_self">Подтвердить регистрацию</a></h3>
    Если вы получили это письмо по ошибке, просто игнорируйте его.

springdoc:
  show-actuator: true
  api-docs:
    path: /api-docs