spring:

  datasource:
    driver-class-name: org.postgresql.Driver

    # for docker db
    #    username: demouser
    #    password: demopassword
    #    url: jdbc:postgresql://localhost:15432/postgres

    # for local db
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        order_by.default_null_ordering: last

  flyway:
    out-of-order: true

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
jwt:
  token:
    secret: jwtdevblog
    expired: 3600000
