spring:

  datasource:
    username: demouser
    password: demopassword
    url: jdbc:postgresql://localhost:15432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
#        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  flyway:
    out-of-order: true

jwt:
  token:
    secret: jwtdevblog
    expired: 3600000
