spring:
  datasource:
    username: test
    password: test
  mail:
    password: springboot
    username: duke
    host: 127.0.0.1
    port: 3025 # default protocol port + 3000 as offset
    protocol: smtp
    test-connection: false # avoid setting this to true when using a per-test-method GreenMail server
