name: Ci-Integration-Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ development, master ]

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Up container with Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: mvn_verify
        run: mvn -B verify -DskipUTs=true --file pom.xml -DexcludeRegex=**/*ST