# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Ci-Github-Pipelines

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  Build_Package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Up container with Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk/openjdk11:alpine-jre'
        cache: maven
    - name: Mvn_Build_Package
      run: mvn -B package --file pom.xml
