name: Ci-Github-Pipelines

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ development ]

jobs:
  Build_Package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Up container with Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Mvn_Build_Package
      run: mvn -B package --file pom.xml
